// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmployeeManagement_.Entity
{
    public partial class EmployeeManagementDetails
    {
        [Key]
        public int Employee_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Full_Name { get; set; }
        [Required]
        [StringLength(30)]
        public string User_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        public string Department { get; set; }
        [Required]
        [StringLength(20)]
        public string Matricule { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        public int Phone_Number { get; set; }
        [Required]
        [StringLength(10)]
        public string Gender { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }
    }
}